app/routes.py
import os
from flask import send_file, Blueprint, request, redirect, url_for, render_template, flash, current_app, session, jsonify
from werkzeug.utils import secure_filename
from flask_login import login_required, current_user, login_user, logout_user
import pandas as pd
from io import BytesIO
from app import db
from app.models import User, Employee, Owner, RoleType, ExperienceLevel, Sex, InvolvementType, ConditionType, TargetType, ProjectRoles, Favourite_projects, Response
from app.models import ProjectScopeType, Favourite_employees, ProjectTargetType, ProjectStageType, ProjectConditionsType, Project, ProjectEmployee, Invite, StatusInvite
from app import login_manager 
from app.file_utils import allowed_file, unique_filename
from datetime import datetime
from sqlalchemy import func, not_

main_bp = Blueprint('main', __name__)

login_manager.login_view = 'main.home'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

"""
Обрабатывает корневой маршрут. Перенаправляет на выбор типа пользователя или дашборд,
в зависимости от того, зарегистрирован ли пользователь как сотрудник или владелец.
"""
@main_bp.route('/')
def home():
    if not current_user.is_authenticated:
        return redirect(url_for('main.login'))

    owner_exists = Owner.query.filter_by(user_id=current_user.id).first()
    employee_exists = Employee.query.filter_by(user_id=current_user.id).first()  

    if not owner_exists and not employee_exists:
        return redirect(url_for('main.type_user'))
    else:
        if owner_exists:
            return redirect(url_for('main.general'))
        elif employee_exists:
            return redirect(url_for('main.general'))
        else:
            flash('Непредвиденная ошибка.', 'warning')


"""
Отображает страницу входа. Обрабатывает отправку формы и логин пользователя.
"""
@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        if not email or not password:
            flash('Пожалуйста, заполните оба поля.', 'warning')
            return render_template('login.html', login=True)

        user = User.query.filter_by(login=email).first()

        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('main.home'))
        else:
            flash('Неверный email или пароль.', 'danger')

    return render_template('login.html', login=True)


"""
Обрабатывает регистрацию нового пользователя. Создает нового User и выполняет вход.
"""
@main_bp.route('/registration', methods=['GET', 'POST'])
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        if not email or not password:
            flash('Пожалуйста, заполните все поля.', 'warning')
            return render_template('login.html')

        existing_user = User.query.filter_by(login=email).first()
        if existing_user:
            flash('Пользователь с таким email уже зарегистрирован.', 'danger')
            return render_template('login.html')

        new_user = User(login=email)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user)
        return redirect(url_for('main.home'))

    return render_template('login.html')


"""
Выход пользователя из системы и редирект на домашнюю страницу.
"""
@main_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

"""
Позволяет авторизованному пользователю выбрать тип — сотрудник или владелец.
Создает соответствующую запись в таблице Employee или Owner.
"""
@main_bp.route('/type_user', methods=['GET', 'POST'])
@login_required
def type_user():
    if request.method == 'POST':
        user_type = request.form.get('user_type')

        if user_type == "employee":
            employee = Employee(user_id=current_user.id)
            db.session.add(employee)
            db.session.commit()
            return redirect(url_for('main.home'))

        elif user_type == "owner":
            owner = Owner(user_id=current_user.id)
            db.session.add(owner)
            db.session.commit()
            return redirect(url_for('main.home'))

        else:
            flash('Непредвиденная ошибка.', 'warning')

    return render_template('type_user.html')


"""
Главная страница дашборда. Если пользователь — владелец, отображает сотрудников для подбора команды.
Если пользователь — сотрудник, отображает доступные проекты. Включает фильтрацию и избранное.
"""
@main_bp.route('/general', methods=['GET', 'POST'])
@login_required
def general():
    owner_exists = Owner.query.filter_by(user_id=current_user.id).first()
    employee_exists = Employee.query.filter_by(user_id=current_user.id).first()
    count_notifications = None
    roles = RoleType.query.all()
    scopes = ProjectScopeType.query.all()

    if owner_exists:
        count_notifications = (
            db.session.query(func.count(Invite.id))
            .join(Project, Project.id == Invite.project_id)
            .join(StatusInvite, StatusInvite.id == Invite.status_id)
            .filter(Project.owner_id == owner_exists.id)
            .filter(StatusInvite.label != "Отправлен")
            .filter(Invite.checked == False)
            .scalar()
        )
        if count_notifications > 100:
            count_notifications = "99+"
        experiences = ExperienceLevel.query.all()
        involvements = InvolvementType.query.all()
        conditionss = ConditionType.query.all()
        targets = TargetType.query.all()

        employees = Employee.query.all()

        favourites = Favourite_employees.query.filter_by(owner_id=owner_exists.id).all()
        fav_ids = {fav.employee_id for fav in favourites}
        for emp in employees:
            emp.fav = emp.id in fav_ids

        return render_template('general.html', owner=True, count_notifications=count_notifications, roles=roles,
        conditionss=conditionss, scopes=scopes, experiences=experiences, involvements=involvements, targets=targets,
        employees=employees)
    elif employee_exists:
        count_notifications = (
            db.session.query(func.count(Invite.id))
            .join(StatusInvite, StatusInvite.id == Invite.status_id)
            .filter(Invite.employee_id == employee_exists.id)
            .filter(StatusInvite.label == "Отправлен")
            .scalar(
        ))
        if count_notifications > 100:
            count_notifications = "99+"
        conditionss = ProjectConditionsType.query.all()
        targets = ProjectTargetType.query.all()
        stages = ProjectStageType.query.all()

        projects = Project.query.all()
        favourites = Favourite_projects.query.filter_by(employee_id=employee_exists.id).all()
        fav_project_ids = {fav.project_id for fav in favourites}
        for project in projects:
            project.fav = project.id in fav_project_ids
            project_roles = ProjectRoles.query.filter_by(project_id=project.id).all()
            role_labels = [RoleType.query.get(role.role_id).label for role in project_roles]
            project.roles_str = ', '.join(role_labels)

            project_employees = ProjectEmployee.query.filter_by(project_id=project.id).all()
            employees_info = []
            for pe in project_employees:
                employee = Employee.query.get(pe.employee_id)
                if employee:
                    full_name = f"{employee.name} {employee.surname}".strip()
                    employees_info.append((employee.id, full_name))

            project.employees = employees_info 

        return render_template('general.html', count_notifications=count_notifications, owner=False, roles=roles, scopes=scopes, stages=stages, targets=targets, conditionss=conditionss, projects=projects)
    else:
        pass


"""
Отображает страницу профиля текущего пользователя (владельца или сотрудника).
Показывает информацию и связанные проекты, отклики или приглашения.
"""
@main_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    count_notifications = None
    owner_exists = Owner.query.filter_by(user_id=current_user.id).first()
    employee_exists = Employee.query.filter_by(user_id=current_user.id).first()
    if owner_exists:
        count_notifications = (
            db.session.query(func.count(Invite.id))
            .join(Project, Project.id == Invite.project_id)
            .join(StatusInvite, StatusInvite.id == Invite.status_id)
            .filter(Project.owner_id == owner_exists.id)
            .filter(StatusInvite.label != "Отправлен")
            .filter(Invite.checked == False)
            .scalar()
        )
        if count_notifications > 100:
            count_notifications = "99+"
        data = Owner.query.filter_by(user_id=current_user.id).first()
        projects = Project.query.filter_by(owner_id=owner_exists.id).all()
        for project in projects:
            project_roles = ProjectRoles.query.filter_by(project_id=project.id).all()
            role_labels = [RoleType.query.get(role.role_id).label for role in project_roles]
            project.roles_str = ', '.join(role_labels)

            project_employees = ProjectEmployee.query.filter_by(project_id=project.id).all()
            employees_info = []
            for pe in project_employees:
                employee = Employee.query.get(pe.employee_id)
                if employee:
                    full_name = f"{employee.name} {employee.surname}".strip()
                    employees_info.append((employee.id, full_name))

            project.employees = employees_info

app/templates/edit_project.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/style/edit_profile.css">
    <title>Редактор проекта</title>
</head>
<body>
    <header>
        <div class="header-contaner">
            <div class="header-left">
                <a href="/general">
                    <img src="../static/image/favicon.svg" alt="">
                </a>
                <a href="/notifications" class="notification-button">
                    {% if owner %}Ответы участников{% else %}Мои приглашения{% endif %}
                    {% if count_notifications %}
                        <span class="notification-count"> {{ count_notifications }} </span>
                    {% endif %}
                </a>
            </div>
            <div class="header-right">
                <a class="header-button" href="{% if owner %} /project_add {% else %} {{ url_for('main.edit_profile') }} {% endif %}"> 
                    {% if owner %}Создать проект{% else %}Заполнить профиль{% endif %} 
                </a>
                <a href="/favourite">
                    <img src="../static/image/favourite.svg" alt="">
                </a>
                <a href="{{ url_for('main.profile') }}">
                    <img src="../static/image/profile.svg" alt="" class="last">
                </a>
            </div>
        </div>
    </header>
    <div class="main-container-area">
        <div class="main-container">
            <div class="profile-label">
                {% if create %}
                <h1>Создание проекта</h1>
                {% else %}
                <h1>Редактирование проекта</h1>
                <a href="/remove_project?id={{ project.id }}">Удалить</a>
                {% endif %}
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <div class="flash-message">
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <div class="profile-edit-data-contaner">
                <form action="{% if create %}{{ url_for('main.project_add') }}{% else %}/edit_project?id={{ project.id }}{% endif %}" 
                    method="post" enctype="multipart/form-data" class="profile-form">

                    <div class="input-block">
                        <p>Название проекта</p>
                        <input type="text" name="title" placeholder="Введите название проекта"
                            value="{% if not create %}{% if project.title %}{{project.title}}{%endif%}{%endif%}" required>
                    </div>
                    
                    <div class="input-block">
                        <p>Сфера проекта</p>
                        <select name="scope_id" required>
                            {% if not create %}
                            {% if not project.scope_id %}
                                <option value="" disabled selected hidden>Выберите сферу проекта</option>
                            {% endif %}
                            {% endif %}
                            {% for scope in scopes %}
                                <option value="{{ scope.id }}" {% if not create%}{% if scope.id == project.scope_id %}selected{% endif %}{% endif %}>
                                    {{ scope.label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-block-about">
                        <p>Расскажите о проекте</p>
                        <textarea maxlength="2000" class="input-owner-textarea" name="about" placeholder="Расскажите о себе" required>{% if not create %}{% if project.about %}{{project.about}}{%endif%}{%endif%}</textarea>
                    </div>

                    <div id="role-select-wrapper">
                        <div class="custom-select-row">
                            <div class="custom-select-block">
                                <p>Роль, которую вы ищете</p>
                                <select name="role_id" required>
                                    {% if not create %}
                                    {% if not project.roles %}
                                    <option value="" disabled selected hidden>Выберите роль</option>
                                    {% endif %}
                                    {% endif %}
                                    {% for role in roles %}
                                        <option value="{{ role.id }}" {% if not create%}{% if role.id == project.roles[0] %}selected{% endif %}{% endif %}>
                                            {{ role.label }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button type="button" class="custom-circle-button" onclick="addRoleSelect()">+</button>
                        </div>
                        {% if not create %}
                        {% if project.roles|length > 1 %}
                        {% for role_proj in project.roles[1:] %}
                        <div class="custom-select-row">
                            <div class="custom-select-block">
                                <p>Роль, которую вы ищете</p>
                                <select name="role_id" required>
                                    <option value="" disabled selected>Выберите роль</option>
                                    {% for role in roles %}
                                        <option value="{{ role.id }}" {% if not create%}{% if role.id == role_proj %}selected{% endif %}{% endif %}>
                                            {{ role.label }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button type="button" class="custom-remove-button" onclick="removeRoleSelect(this)">×</button>
                        </div>
                        {% endfor %}
                        {% endif %}
                        {% endif %}
                    </div>
                                        
                    <div class="input-block">
                        <p>На каком этапе проект?</p>
                        <select name="stage_id" required>
                            {% if not create %}
                            {% if not project.stage_id %}
                                <option value="" disabled selected>Выберите этап проекта</option>
                            {% endif %}
                            {% endif %}
                            {% for stage in stages %}
                                <option value="{{ stage.id }}" {% if not create%}{% if stage.id == project.stage_id %}selected{% endif %}{% endif %}>
                                    {{ stage.label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-block">
                        <p>Условия</p>
                        <select name="conditions_id" required>
                            {% if not create %}
                            {% if not project.stage_id %}
                                <option value="" disabled selected>Выберите условия проекта</option>
                            {% endif %}
                            {% endif %}
                            {% for conditions in conditionss %}
                                <option value="{{ conditions.id }}" {% if not create%}{% if conditions.id == project.conditions_id %}selected{% endif %}{% endif %}>
                                    {{ conditions.label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-block">
                        <p>Цель проекта</p>
                        <select name="target_id" required>
                            {% if not create %}
                            {% if not project.stage_id %}
                                <option value="" disabled selected>Выберите цель проекта</option>
                            {% endif %}
                            {% endif %}
                            {% for target in targets %}
                                <option value="{{ target.id }}" {% if not create%}{% if target.id == project.target_id %}selected{% endif %}{% endif %}>
                                    {{ target.label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input-block-about">
                        <p>Опишите, какого участника команды вы ищите</p>
                        <textarea maxlength="1000" class="input-owner-textarea" name="employee_description" placeholder="Расскажите об участнике" required>{% if not create %}{% if project.employee_description %}{{project.employee_description}}{%endif%}{%endif%}</textarea>
                    </div>

                    <button type="submit" class="btn">{% if create %}Создать проект {% else %} Сохранить {% endif %}</button>
                </form>

            </div>
        </div>
    </div>

<script>
    let roleSelectCount = 1;

    function addRoleSelect() {
        const wrapper = document.getElementById('role-select-wrapper');
        const newBlock = document.createElement('div');
        newBlock.className = 'custom-select-row';
        newBlock.innerHTML = `
            <div class="custom-select-block">
                <p>Роль, которую вы ищете</p>
                <select name="role_id" required>
                    <option value="" disabled selected>Выберите роль</option>
                    {% for role in roles %}
                        <option value="{{ role.id }}">{{ role.label }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="button" class="custom-remove-button" onclick="removeRoleSelect(this)">×</button>
        `;
        wrapper.appendChild(newBlock);
        roleSelectCount++;
    }

    function removeRoleSelect(button) {
        const block = button.parentElement;
        block.remove();
    }
</script>
</body>
</html>

app/templates/employee.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/style/employee.css">
    <title>{{ employee.surname if employee.surname else ''}} {{ employee.name if employee.name else ''}} </title>
</head>
<body>
    <header>
        <div class="header-contaner">
            <div class="header-left">
                <a href="/general">
                    <img src="../static/image/favicon.svg" alt="">
                </a>
                <a href="/notifications" class="notification-button">
                    {% if owner %}Ответы участников{% else %}Мои приглашения{% endif %}
                    {% if count_notifications %}
                        <span class="notification-count"> {{ count_notifications }} </span>
                    {% endif %}
                </a>
            </div>
            <div class="header-right">
                <a class="header-button" href="{% if owner %} /project_add {% else %} {{ url_for('main.edit_profile') }} {% endif %}"> 
                    {% if owner %}Создать проект{% else %}Заполнить профиль{% endif %} 
                </a>
                <a href="/favourite">
                    <img src="../static/image/favourite.svg" alt="">
                </a>
                <a href="{{ url_for('main.profile') }}">
                    <img src="../static/image/profile.svg" alt="" class="last">
                </a>
            </div>
        </div>
    </header>
    <div class="main-container-area">
        <div class="main-container">
            {% if owner %}
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <div class="flash-message">
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            {% endif %}
            <div class="profile-contaner">
                <h1>{{ employee.role.label }}</h1>
                <h2>{{ employee.surname }} {{ employee.name }} {{ employee.middlename }}</h2>
                <h3>Обо мне</h3>
                <p class="about">{{ employee.about }}</p>
                <div class="twice-grid-contaner">
                    <div class="twice-grid">
                        <p class="title-grid">Опыт</p>
                        <p class="value-grid">{{ employee.experience.label }}</p>
                    </div>  
                    <div class="twice-grid">
                        <p class="title-grid">Вовлеченность</p>
                        <p class="value-grid">{{ employee.involvement.label }}</p>
                    </div>  
                </div>
                <div class="twice-grid-contaner">
                    <div class="twice-grid">
                        <p class="title-grid">Сфера проекта</p>
                        <p class="value-grid">{{ employee.scope.label }}</p>
                    </div>  
                    <div class="twice-grid">
                        <p class="title-grid">Условия</p>
                        <p class="value-grid">{{ employee.conditions.label }}</p>
                    </div>  
                </div>
                <div class="twice-grid-contaner">
                    <div class="twice-grid">
                        <p class="title-grid">Телефон</p>
                        <p class="value-grid">{{ employee.phone }}</p>
                    </div>  
                    <div class="twice-grid">
                        <p class="title-grid">Telegram</p>
                        <p class="value-grid">{{ employee.telegram_nickname }}</p>
                    </div>  
                </div>
                <div class="once-grid-contaner">
                    <p class="title-grid">Цель</p>
                    <p class="value-grid">{{ employee.target.label }}</p>
                </div>
                <h3>Какой проект я ищу:</h3>
                <p class="about">{{ employee.about_project }}</p>
                {% if owner %}
                <button class="btn">Пригласить в команду</button>
                {% endif %}
            </div>
            {% if owner %}
            <div class="invite-fav-contaner">
                <button class="btn">Пригласить</button>
                <button class="favourite-contaner {% if fav %} active {% endif %}" data-employee-id="{{ employee.id }}">
                    <img src="{% if fav %} ../static/image/favourite-active.svg {% else %} ../static/image/favourite.svg {% endif %}" alt="">
                </button>
            </div>
            {% endif %}
        </div>
    </div>
    {% if owner %}
    <div id="modal" class="modal">
        <div class="modal-content">
            <button class="close" aria-label="Закрыть">
            <img src="{{ url_for('static', filename='image/exit.svg') }}" alt="закрыть">
            </button>
            {% if projects %}
            {% for project in projects %}
            <a href="/add_invite?emp_id={{ employee.id }}&project_id={{ project.id }}" style="text-decoration: none;">
                <div class="project-contaner">
                    <div class="project-contaner-top">
                        <div class="project-contaner-category">
                            {% if project.scope_id %}
                                <p>{{ project.scope.label }}</p>
                            {% endif %}
                            {% if project.target_id %}
                                <p>{{ project.target.label }}</p>
                            {% endif %}
                            {% if project.stage_id %}
                                <p>{{ project.stage.label }}</p>
                            {% endif %}
                            {% if project.conditions_id %}
                                <p>{{ project.conditions.label }}</p>
                            {% endif %}
                        </div>
                    </div>
                    <p class="project-title">{{ project.title }}</p>
                    <h3 class="project-roles">{{ project.roles_str }}</h3>
                    <p class="project-about">{{ project.about }}</p>
                </div>
            </a>
                {%endfor%}
            {% else %}
            <div class="modal-not-data">
                <img src="../static/image/create_project.png" alt="">
                <h2>Создайте проект</h2>
                <p>{% if not project_yes %}У вас еще нет ни одного проекта. Создайте проект, чтобы приглашать участников в команду{% else %}У вас нет ни одного проекта, в котором данный пользователь не принимает участие{% endif %}</p>
                <a href="/project_add">Создайте проект</a>
            </div>
            {% endif %}
        </div>
    </div>

    <script>
    document.addEventListener('DOMContentLoaded', () => {
        const modal       = document.getElementById('modal');
        const openButtons = document.querySelectorAll('.btn');
        const closeBtn    = modal.querySelector('.close');

        openButtons.forEach(btn =>
            btn.addEventListener('click', () => modal.classList.add('show'))
        );

        closeBtn.addEventListener('click', () =>
            modal.classList.remove('show')
        );

        modal.addEventListener('click', e => {
            if (e.target === modal) modal.classList.remove('show');
        });

        document.querySelectorAll(".favourite-contaner").forEach(button => {
            button.addEventListener("click", async () => {
            const empId = button.dataset.employeeId;
            const img = button.querySelector('img');

            try {
                const res = await fetch("/favourite_add", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ id: empId }),
                });
                const data = await res.json();

                if (res.ok) {
                if (data.action === "added") {
                    button.classList.add("active");
                    img.src = "../static/image/favourite-active.svg";
                } else if (data.action === "removed") {
                    button.classList.remove("active");
                    img.src = "../static/image/favourite.svg";
                }
                } else {
                console.error("Ошибка:", data.error);
                }
            } catch (err) {
                console.error("Ошибка запроса:", err);
            }
            });
        });
    });
    </script>
    {% endif %}
</body>
</html>

app/templates/type_user.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="../static/image/favicon.svg" type="image/svg+xml">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/style/type_user.css">
    <title>Тип пользователя</title>
</head>
<body>
    <div class="main-container">
        <div class="login-header">
            <img src="../static/image/header-login.svg" alt="">
        </div>
        <div style="width: 100%; height: calc(100vh - 96px); display: flex; justify-content: center;">
            <div class="login-all-contaner">
                <h1>Что вы ищите?</h1>
                <form class="form-container" action="/type_user" method="post">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <div class="radio-group">
                        <label>
                            <input type="radio" name="user_type" value="employee" required>
                            <div class="radio-card">
                                <h2>Хочу присоединиться к существующему проекту</h2>
                                <p>Профиль участника проекта</p>
                            </div>
                        </label>

                        <label>
                            <input type="radio" name="user_type" value="owner">
                            <div class="radio-card">
                                <h2>Ищу команду для своего проекта</h2>
                                <p>Профиль создателя проекта</p>
                            </div>
                        </label>
                    </div>

                    <div class="button-contaner">
                        <button type="submit" class="submit-button">Продолжить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>